name: "Build CI"

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  CI_DEPLOY_USERNAME: ${{ secrets.CI_DEPLOY_USERNAME }}
  CI_DEPLOY_PASSWORD: ${{ secrets.CI_DEPLOY_PASSWORD }}

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.ref == 'refs/heads/main' && format('ci-default-branch-{0}-{1}', github.sha, github.workflow) ||
    format('ci-pr-{0}-{1}', github.ref, github.workflow) }}
  cancel-in-progress: true

permissions:
  contents: read
  packages: write
  actions: read
  pull-requests: write
  attestations: write
  id-token: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Java setup
        uses: ./.github/actions/java-setup

#      - name: Configure git
#        uses: ./.github/actions/configure-git

#      - name: Download deps and plugins
#        run: mvn de.qaware.maven:go-offline-maven-plugin:resolve-dependencies

      - name: Build and Deploy
        uses: ./.github/actions/build-deploy
        with:
          branch: ${{ github.ref_name }}
