name: "Java setup"
description: "Common steps for Java setup"

inputs:
  project-path:
    description: 'Path to the Maven project'
    required: true

runs:
  using: "composite"
  steps:
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: 21
        distribution: 'temurin'
#        server-id: ossrh
#        server-username: ${{ env.CI_DEPLOY_USERNAME }}
#        server-password: ${{ env.CI_DEPLOY_PASSWORD }}

#    - name: Set up Maven
#      uses: s4u/setup-maven-action@v1.18.0
#      with:
#        maven-version: '3.8.8'

    - name: Cache Maven dependencies
      uses: actions/cache@v4
      env:
        cache-name: cache-mvn-deps
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles(format('{0}/pom.xml', inputs.project-path)) }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Show versions
      shell: bash
      run: | 
        java -version
        mvn -version