name: backward-compatibility-plugin
description: backward-compatibility-plugin
inputs:
  branch:
    description: 'Branch name to determine build or deploy'
    required: false
    default: ''
runs:
  using: "composite"
  steps:
    - name: Build or Deploy
      shell: bash
      run: |
        if [[ "${{ inputs.branch }}" == "main" ]]; then
          mvn -B -e -U deploy -DskipTests=true -DskipITs=true -s ./settings.xml
        else
          mvn -B -e -U clean install
        fi